version: '3'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    networks:
      - app-network
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - wordpress-db-data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    depends_on:
      - db
    image: wordpress:5.9.2-fpm-alpine
    container_name: wordpress
    networks:
      - app-network
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress-web-data:/var/www/html
      - ./wordpress/htaccess:/var/www/html/.htaccess
    expose:
      - 9000

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    networks:
      - app-network
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress-web-data:/var/www/html
      - ./data/certbot/conf:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/options-ssl-nginx.conf:/etc/nginx/conf.d/options-ssl-nginx.conf
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - wordpress-web-data:/var/www/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --force-renewal; sleep 12h & wait $${!}; done;'"

volumes:
  certbot-etc:
  wordpress-web-data:
  wordpress-db-data:


networks:
  app-network:
    driver: bridge
