version: '3'
services:
  # WORDPRESS
  # based on https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-docker-compose
  wordpress-db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - wordpress-db-data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    depends_on:
      - wordpress-db
    image: library/wordpress:5.7.2-php7.4-apache
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress-web-data:/var/www/html
      - ./wordpress/htaccess:/var/www/html/.htaccess
    ports:
      - "9000:80"
volumes:
  wordpress-web-data:
  wordpress-db-data:
