version: '3'
services:
  odoo:
    image: quay.io/numigi/odoo-public:12.22
    restart: unless-stopped
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./log:/var/log/odoo
      - ./client:/mnt/extra-addons/client
      - ./odoo-specific.conf:/etc/odoo/odoo-specific.conf
    expose:
      - 8069
      - 8071
    ports:
      - "8069:8069"
      - "8071:8071"
    environment:
      - LOG_ODOO=/var/log/odoo
      - SPECIFIC_ODOO_RC=/etc/odoo/odoo-specific.conf
    depends_on:
      - db
    command: odoo
  db:
    image: postgres:11.9
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    expose:
      - 5432
  http:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./landing_page:/etc/nginx/landing_page
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
    depends_on:
      - odoo
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  odoo-web-data:
  odoo-db-data:
  certbot-conf:
  certbot-www: