version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - wordpress-db-data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    depends_on:
      - db
    image: wordpress:5.9.2-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress-web-data:/var/www/html

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress-web-data:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/options-ssl-nginx.conf:/etc/nginx/conf.d/options-ssl-nginx.conf

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress-web-data:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email ec@edithcourtial.com --agree-tos --no-eff-email --force-renewal -d edithcourtial.com -d www.edithcourtial.com

volumes:
  certbot-etc:
  wordpress-web-data:
  wordpress-db-data:
